language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

addons:
  apt:
    packages:
      - libssl1.0.0

before_install:
  - wget https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-Linux-ubuntu-$(lsb_release -rs).deb
  - sudo dpkg -i seabolt-1.7.4-Linux-ubuntu-$(lsb_release -rs).deb
  - rm seabolt-1.7.4-Linux-ubuntu-$(lsb_release -rs).deb